### ISSUE TITLE
StarNub Integration Potential

### ISSUE THREAD

**Issue by Underbalanced** [wizzomafizzo/starcheat#116]
I see that you can the assets and such. This could be a useful library or tool integrated into Starnub, by having indexed item list to give. Additionally perhaps a GUI to build out a Starbound variant of weapons info that can be injected into the give item packet.

StarNub/StarNubMain#3

I have fully integrated python into StarNub. You are able to use all StarNub libraries, and you are also able to write Python libraries that i can import into StarNub internally behind commands and plugins.

**Comment by chrmoritz** [comment]
Note that Jython implements python 2.7, which is not compatible with current starcheat code, which requires python 3.3+

**Comment by Underbalanced** [comment]
Oh yes I forgot to look at your version. I would contribute with integration to your project. What is it specifically about Py 3.3 that Starcheat uses and is not backward compatible?

**Comment by chrmoritz** [comment]
Python 3 itself is not backward compatible to Python 2 see https://wiki.python.org/moin/Python2orPython3

**Comment by wizzomafizzo** [comment]
I'm not against accepting a patch if it's possible to make assets.py backwards compatible with 2, I know py-starbound does a similar thing for us, but it is a real beast now and I'm not confident it would work.

There was never any killer feature in 3 that made me pick it over 2 but even ignoring the work involved I'm not keen on reverting to 2, it's totally possible as well we use version 3 features without realising too.

You may have better luck with saves.py since it has no dependencies, happy to accept a patch here to make it work.

**Comment by wizzomafizzo** [comment]
Please let us know if you make any progress with this, I will reopen

**Comment by Underbalanced** [comment]
I stopped development of StarNub and have created my own game from the code. Starbound as a game did not deserve so many hours from me, nothing will help make the game better.
