### ISSUE TITLE
(Upbeat Girraffe) No "starbound.config" file.

### ISSUE THREAD

**Issue by Pit150** [wizzomafizzo/starcheat#147]
OS: Windows 8.1 (32Bit)
I go to open StarCheat and then select Starbound. Error happens, making me unable to use it.
Last version that worked fine for me was **Enraged Koala**'s starcheat.
![error](https://cloud.githubusercontent.com/assets/10855035/6049276/69f71a4c-ac8c-11e4-87a2-41c6b8bbea0b.PNG)
Error message.
![starbound](https://cloud.githubusercontent.com/assets/10855035/6049278/6cf6e6fa-ac8c-11e4-9c93-302d0c99780c.PNG)
What Windows Explorer says about it.
![starcheat says](https://cloud.githubusercontent.com/assets/10855035/6049280/6fac68f2-ac8c-11e4-98d4-b8a0d4994980.PNG)
What StarCheat says about it.
![version](https://cloud.githubusercontent.com/assets/10855035/6049282/72a5f7c6-ac8c-11e4-96b8-1ab5b06f8f0a.PNG)
Starcheat Version.

**Comment by chrmoritz** [comment]
What did you do? o.O
This is not the Upbeat Giraffe version in your screenshot. It's the folder layout of the very old stable version. 
I would recommend to make a clean reinstall of Starbound from Steam and use a binary version of [starcheat from here](https://github.com/wizzomafizzo/starcheat/releases) instead of trying to compile it yourself.

**Comment by Pit150** [comment]
1.9 crashes instead, but end result is same: Can't use it. Meh, I could just use starbounds's /spawnitem command.
