### ISSUE TITLE
Race change bug

### ISSUE THREAD

**Issue by ShanKanis** [wizzomafizzo/starcheat#168]
So, I changed race of my character from Novakid to Human. When I launched the game I got new quest. "There's no place like home" This quest is the first one you get when you start the game. So game thinks that when I changed race, I started new character. Any ideas what can I do to at least delete that quest from journal?

**Comment by wizzomafizzo** [comment]
thanks for the report. at this stage, no, sorry :( the quests are stored in the metadata file not the player file. starcheat support reading/writing this file but it doesn't actually let you do anything with it yet

i had plans to add a quest management dialog to starcheat but wasn't sure what the demand for it would be. i don't like the idea of adding an exception to clear out this quest on species change since it could be a pain to keep updated

i have changed this ticket to include the new quest management feature. i will probably bump it up the priority list but couldn't tell you when it will be done. keep an eye on this ticket

**Comment by wizzomafizzo** [comment]
Moving the quest management component of this to #171

**Comment by wizzomafizzo** [comment]
Latest commits now add a quest management dialog. Can't say quite yet when it will be out but this will be included in the next release. Happy to get feedback on it
